{% raw %}
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip poetry
    - name: Build assets
      run: poetry build

    - name: Upload assets to release
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/**

    - name: Upload assets to PyPi
      # Hack from https://github.community/t/how-can-i-test-if-secrets-are-available-in-an-action/17911/11
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      if: ${{ env.PYPI_USERNAME != null && env.PYPI_PASSWORD != null}}
      run: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
{% endraw %}
