name: Autoupdate
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Run every month
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip cookiecutter poetry
      - name: Update template
        run: make all
      - name: Check if we should commit
        id: commit_check
        run: |
          if git diff --quiet
          then
            echo "::set-output name=should_commit::false"
          else
            echo "::set-output name=should_commit::true"
          fi
      - name: Commit updated lockfiles
        uses: EndBug/add-and-commit@v7
        if: ${{ contains(steps.commit_check.outputs.should_commit, 'true') }}
        with:
          default_author: github_actions
          message: ":robot: :arrow_up: Updated deps and lockfile\n\nThis is an automated action"
