name: Autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Run every single day
jobs:
  with_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip cookiecutter poetry
      - name: Build example template
        run: cookiecutter . --no-input
      - name: Update example template
        run: poetry update
        working-directory: ./cool-example
      - name: Check for differences
        run: |
          ! diff \
          '../{{ cookiecutter.pypi_name }}/{% if cookiecutter.add_docs == "yes" %}poetry.lock{% endif %}' \
          poetry.lock
        working-directory: ./cool-example
      - name: Commit updated
        run: cp poetry.lock '../{{ cookiecutter.pypi_name }}/{% if cookiecutter.add_docs == "yes" %}poetry.lock{% endif %}'
        working-directory: ./cool-example
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: ":robot: :arrow_up: Updated deps and lockfile\n\nThis is an automated action"
  without_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip cookiecutter poetry
      - name: Setup env
        run: |
          echo "default_context:\n  add_docs: no\n" > env.yml
      - name: Build example template
        run: cookiecutter . --no-input --config-file env.yml
      - name: Update example template
        run: poetry update
        working-directory: ./cool-example
      - name: Check for differences
        run: |
          ! diff \
          '../{{ cookiecutter.pypi_name }}/{% if cookiecutter.add_docs == "no" %}poetry.lock{% endif %}' \
          poetry.lock
        working-directory: ./cool-example
      - name: Commit updated
        run: cp poetry.lock '../{{ cookiecutter.pypi_name }}/{% if cookiecutter.add_docs == "no" %}poetry.lock{% endif %}'
        working-directory: ./cool-example
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: ":robot: :arrow_up: Updated deps and lockfile\n\nThis is an automated action"
