name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip cookiecutter poetry poethepoet
      - name: Build example
        run: cookiecutter . --no-input
      - name: Cd to example
        run: cd cool-example
      - name: Make sure the lockfile, etc are fully up-to-date
        run: |
            poetry update
            diff pyproject.toml '../{{ cookiecutter.pypi_name }}/{% if cookiecutter.add_docs == "yes" %}poetry.lock{% endif %}'
      - name: Install and build wheel for example
        run: |
          poetry install
          poetry build
          poe format
          poe docs
