name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip copier poetry poethepoet
      - name: Create default options
        run: echo '{"add_docs":true,"author":"Bryan Hu","email":"bryan.hu.2020@gmail.com","is_app":true,"module_name":"cool_example","project_description":"","project_name":"Cool Example","pypi_name":"cool-example","username":"ThatXliner"}' > env.yml

      - name: Build example template
        run: copier copy gh:ThatXliner/pyt2 . -a env.yml --defaults
      - name: Build example
        run: |
          cd cool-example
          poetry install
          poetry build
          poe format
          poe docs
