name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip copier poetry poethepoet
      - name: Create default options
        run: make setup-env

      - name: Build example template
        run: copier copy gh:ThatXliner/pyt2 . -a .copier-answers.yml --defaults --vcs-ref HEAD
      - name: Build example
        working-directory: cool-example
        run: |
          poetry install
          poetry build
      - name: Run example tasks
        working-directory: cool-example
        run: |
          poe docs
          poe style
          poe codebase
          poe test
