name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip cookiecutter poetry poethepoet
      - name: Build example template
        run: cookiecutter . --no-input
      - name: Build example
        run: |
          cd cool-example
          poetry install
          poetry build
          poe format
